#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Comic Sans"
title: "Comic Sans"

# Short bio or description (displayed in the header)
description: Welcome to nerdwana

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/600949

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: contact@nerdwana.net
  facebook:
  flickr:
  github: ComicSans/ComicSans.netlify
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: users/362364/comic-sans?tab=profile
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: #comicsans

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: # UA-28060151-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://nerdwana.com
email: contact@nerdwana.net

author: Tobias Reithmeier

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: pretty #/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'code'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/_sass
  style: :compressed # Default: :expanded, You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-picture-tag
  - jekyll-multiple-languages-plugin
  - jekyll-tidy
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .ruby-version

include: ['_pages']
excerpt_separator: <!--more-->

# multilanguage configuration
languages: ['en', 'de']
exclude_from_localizations: ["javascript", "images", "css"]
language_default: 'en'
languageNames:
  de: DE
  en: EN

encoding: utf-8

picture:
  source: "/"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

jekyll_tidy:
  exclude: []
  compress_html: true  # or false
